### ISSUE TITLE
Error initializing X-Ray, one of the required parameters was blank.

### ISSUE THREAD

**Issue by HoreaM** [Ephemerality/xray-builder.gui#42]
Hey there, I was trying to generate an XRAY for one of my books and I got the following error:
> An error occurred while building the X-Ray:
Error initializing X-Ray, one of the required parameters was blank.
   at XRayBuilder.Core.XRay.XRay..ctor(String shelfari, String db, String guid, String asin, ISecondarySource dataSource)
   at XRayBuilder.Core.XRay.Logic.XRayService.<CreateXRayAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at XRayBuilderGUI.UI.frmMain.<btnBuild_Run>d__35.MoveNext()

I think the problem is, that for some reason the xray builder is not generating a database name:
> Extracting metadata...
Got metadata!
Database Name: 
UniqueID: 3858833475
ASIN: B003P8Q5QC
Book's Goodreads URL: https://www.goodreads.com/book/show/10371118
Attempting to build X-Ray...

Is there some way around this?
Thanks!

**Comment by Ephemerality** [comment]
The database name comes from the book, it's not generated by the app. Weird that isn't blank but I suppose it shouldn't actually be required anymore anyway. Give this release a try and see if it works:  
https://github.com/Ephemerality/xray-builder.gui/releases/tag/2.1.126

**Comment by HoreaM** [comment]
I'm still getting the following error:

> Extracting metadata...
Got metadata!
Database Name: 
UniqueID: 3858833475
ASIN: B003P8Q5QC
Book's Goodreads URL: https://www.goodreads.com/book/show/10371118
Attempting to build X-Ray...
Loading terms from file...
An error occurred while building the X-Ray:
Error processing XML file: There is an error in XML document (2414, 1176).
If the error contains a (#, #), the first number is the line the error occurred on.
   at XRayBuilder.Core.Libraries.Serialization.Xml.Util.XmlUtil.DeserializeFile[T](String filePath)
   at XRayBuilder.Core.DataSources.Secondary.SecondarySourceFile.GetTermsAsync(String xmlFile, String asin, String tld, Boolean includeTopics, IProgressBar progress, CancellationToken cancellationToken)
   at XRayBuilder.Core.XRay.Logic.XRayService.<CreateXRayAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at XRayBuilderGUI.UI.frmMain.<btnBuild_Run>d__32.MoveNext()

**Comment by HoreaM** [comment]
But that seems to be due to my XML file, generating XRAYs with Goodreads and Roentgen seems to be working now.

**Comment by Ephemerality** [comment]
Yeah seems like there's something wrong with your XML on line 2414. Does it look like it's formatted correctly?

**Comment by HoreaM** [comment]
Yup, fixed it and it works fine now, thanks!
