### ISSUE TITLE
X-Ray Error generating aliases

### ISSUE THREAD

**Issue by HossamElwahsh** [Ephemerality/xray-builder.gui#59]
Keep getting this error generating aliases, every time even with empty alias file

```
3 terms found on Goodreads:
Lily Bloom, Atlas Corrigan, Ryle Kincaid
Character aliases read from C:\Users\Hossam\Downloads\EL3ANTEELX\xray-builder-gui-v2.1.197\ext\B0176M3U10.aliases.
Initial X-Ray built, adding locations and chapters…
Scanning e-book content…
An error occurred while building the X-Ray:
Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, Func`2 selector)
   at XRayBuilder.Core.XRay.Logic.ExcerptHelper.ProcessNotablesForParagraph(String paragraph, Int32 offset, IEnumerable`1 notableClips, List`1 excerpts, Boolean skipNoLikes, Int32 minClipLength) in C:\projects\xray-builder-gui\XRayBuilder.Core\src\XRay\Logic\ExcerptHelper.cs:line 49
   at XRayBuilder.Core.XRay.Logic.XRayService.ExpandFromRawMl(XRay xray, IMetadata metadata, Stream rawMlStream, YesNoPrompt yesNoPrompt, EditCallback editCallback, IProgressBar progress, CancellationToken token) in C:\projects\xray-builder-gui\XRayBuilder.Core\src\XRay\Logic\XRayService.cs:line 245
   at XRayBuilder.Core.XRay.Logic.Build.XRayBuildService.<>c__DisplayClass9_0.<BuildAsync>b__1() in C:\projects\xray-builder-gui\XRayBuilder.Core\src\XRay\Logic\Build\XRayBuildService.cs:line 118
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at XRayBuilder.Core.XRay.Logic.Build.XRayBuildService.BuildAsync(Request request, YesNoPrompt yesNoPrompt, YesNoCancelPrompt yesNoCancelPrompt, EditCallback editCallback, IProgressBar progress, CancellationToken cancellationToken) in C:\projects\xray-builder-gui\XRayBuilder.Core\src\XRay\Logic\Build\XRayBuildService.cs:line 130
   at XRayBuilderGUI.UI.frmMain.btnBuild_Run() in C:\projects\xray-builder-gui\XRayBuilder\src\UI\frmMain.cs:line 212
```

**Comment by Ephemerality** [comment]
Sorry for the delay, this should be fixed in [2.1.198](https://github.com/Ephemerality/xray-builder.gui/releases/tag/2.1.198)
