### ISSUE TITLE
Possible Bug?

### ISSUE THREAD

**Issue by HossamElwahsh** [Ephemerality/xray-builder.gui#60]
Facing this error when building XRay for `B07L8QS5WD`

> An error occurred while building the X-Ray:
> Invalid ConnectionString format for part "\XRAY.entities.B07L8QS5WD.asc", no equal sign found
>    at System.Data.SQLite.SQLiteConnection.ParseConnectionString(SQLiteConnection connection, String connectionString, Boolean allowNameOnly)
>    at System.Data.SQLite.SQLiteConnection.Open()
>    at XRayBuilder.Core.XRay.Logic.Export.XRayExporterSqlite.Create(String path) in C:\projects\xray-builder
-gui\XRayBuilder.Core\src\XRay\Logic\Export\XRayExporterSqlite.cs:line 52
>    at XRayBuilder.Core.XRay.Logic.Export.XRayExporterSqlite.Export(XRay xray, String path, IProgressBar progress, CancellationToken cancellationToken) in C:\projects\xray-builder-gui\XRayBuilder.Core\src\XRay\Logic\Export\XRayExporterSqlite.cs:line 29
>    at XRayBuilderGUI.UI.frmMain.btnBuild_Run() in C:\projects\xray-builder-gui\XRayBuilder\src\UI\frmMain.cs:line 226
> 

[asc files Auto Repair For Dummies&#174;.zip](https://github.com/Ephemerality/xray-builder.gui/files/13454412/asc.files.Auto.Repair.For.Dummies.174.zip)

**Comment by Ephemerality** [comment]
What's the path it's saving the files into?

**Comment by HossamElwahsh** [comment]
> What's the path it's saving the files into?

`C:\Users\<6chars username>\Documents\Portable Apps\Xray\xray-builder-gui-v2.1.198\out\Deanna Sclar\Auto Repair For Dummies&#174;`

**Comment by HossamElwahsh** [comment]
Seems to be related to the file path
Changed path to `C:\Users\<username>\Documents\Portable Apps\Xray\xray-builder-gui-v2.1.198\out\Deanna Sclar\Auto Repair for Dummies\` and it worked successfully

**Comment by Ephemerality** [comment]
Yeah it was probably the HTML-encoded trademark symbol `&#174;` that did it. I should be able to fix that when I get a chance.
